# Docker compose file to bring up app and test containers
# See http://docs.microsoft.com/azure/devops/pipelines/languages/docker for more information
sut:
  build: .
  dockerfile: docs/Dockerfile.test
  links:
    - web
web:
  build: .
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
  dockerfile: Dockerfile